services:
  db:
    image: postgres:latest
    container_name: young-eagle-db
    restart: always
    environment:
      POSTGRES_USER: ye_admin
      POSTGRES_PASSWORD: young_eagles
      POSTGRES_DB: young_eagles
    ports:
        - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ye_admin -d young_eagles"]
      interval: 5s
      timeout: 5s
      retries: 5
  migrate:
    image: migrate/migrate
    volumes:
      - ./internal/database/migrations:/migrations
    command: >
      -source file:///migrations
      -database postgres://ye_admin:young_eagles@db:5432/young_eagles?sslmode=disable
      up
    depends_on:
      - db
    restart: on-failure
  young-eagles:
    build:
      context: ./
      dockerfile: young-eagles.dockerfile
    restart: always
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - DB_NAME=young_eagles_developer
      - DB_HOST=young-eagle-developer.cxwcc8oqmytb.us-east-1.rds.amazonaws.com
      - DB_PORT=5432
      - DB_PASS=3dgeL0rd?!?
      - DB_USER=ye_admin