output = "internal/dbmodels"
no-tests = "true"
no-hooks = "true"
wipe = "true"
add-soft-deletes = "true"
pkgname = "dbmodels"

[psql]
host="young-eagle-developer.cxwcc8oqmytb.us-east-1.rds.amazonaws.com"
sslmode="require"
dbname="young_eagles_developer"
user="ye_admin"
pass="YoungEagles!"

[auto-columns]
deleted = "deleted_ts"
created = "created_ts"
updated = "updated_ts"