// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodels

var TableNames = struct {
	ChildInformation  string
	FlightInformation string
	PilotData         string
	PlaneInformation  string
}{
	ChildInformation:  "child_information",
	FlightInformation: "flight_information",
	PilotData:         "pilot_data",
	PlaneInformation:  "plane_information",
}
